fragment BookingFragment on Booking {
  id
  payment
  status
  rating
  feedBack
  bookingCode
  totalPrice
  startDate
  endDate
  quantity
  customerName
  customerPhone
  note
  homeDelivery
  user {
    id
    name
    avatar {
      fileUrl
      filePath
    }
  }
  carType {
    ...CarTypeFragment
  }
  services {
    ...ServiceFragment
  }
}
