fragment CarFragment on Car {
  id
  carType {
    ...CarTypeFragment
  }
  images {
    fileUrl
    filePath
  }
  carBrand
  transmissionType
  consumption
  features
  name
  rating
  engineType
  manufactureYear
  licensePlate
}
