query GetCarsBy($input: GetCarsByInput!) {
  getCarsBy(input: $input) {
    ok
    error {
      mainReason
      message
    }
    cars {
      ...CarFragment
    }
    pagination {
      totalPages
      totalResults
    }
  }
}
