query GetServicesBy($input: GetServicesByInput!) {
  getServices(input: $input) {
    ok
    error {
      mainReason
      message
    }
    pagination {
      totalPages
      totalResults
    }
    services {
      ...ServiceFragment
    }
  }
}
