query GetUserBy($input: GetUserByInput!) {
  getUserBy(input: $input) {
    ok
    error {
      mainReason
      message
    }
    users {
      id
      avatar {
        fileUrl
        filePath
      }
      email
      verified
      name
      role
      address
      phoneNumber
    }
    pagination {
      totalPages
      totalResults
    }
  }
}
